.pre-commit-config.yaml, pyproject.toml
=> pre-commit autoupdate

pyproject.toml, test-requirements.txt
I hope to convince dependabot to keep test-requirements.txt updated
=> move test dependencies to test-requirements.txt

.mdformat.toml, .pre-commit-config.yaml, README.md
=> add readme

src/btrfs2s3/commands/update.py, src/btrfs2s3/main.py
=> add nontrivial help text

README.md
=> add an example crontab for btrfs2s3 update

src/btrfs2s3/preservation.py, tests/preservation/params_test.py
=> enforce strict order in preservation params

README.md
=> Document quirks when uploading to S3

README.md
=> document versioning

src/btrfs2s3/backups.py, tests/backups/path_test.py
=> breaking change: add naming metadata version

src/btrfs2s3/backups.py, tests/backups/path_test.py
this is for forward compatibility with future support for very large backup streams (#54)
=> breaking change: add sequence number to naming

README.md
=> document future commands

README.md, src/btrfs2s3/commands/update.py, src/btrfs2s3/config.py, tests/config_test.py
=> push api_version from config to code

src/btrfs2s3/_internal/commands/update.py, src/btrfs2s3/_internal/config.py, tests/config_test.py
=> move multiple-snapshots check to config validation

src/btrfs2s3/_internal/commands/update.py, src/btrfs2s3/_internal/config.py, tests/config_test.py
=> move multiple-pipe-through check to config validation

src/btrfs2s3/_internal/btrfsioctl.py, tests/_internal/btrfsioctl/__init__.py, tests/_internal/btrfsioctl/get_subvol_info_test.py, tests/_internal/btrfsioctl/send_test.py, tests/_internal/btrfsioctl/snap_create_v2_test.py, tests/_internal/btrfsioctl/snap_destroy_v2_test.py, tests/_internal/btrfsioctl/subvol_create_v2_test.py
this will be a replacement for btrfsutil. it will be integrated in a later commit.
=> refactor(ioctl): add a btrfs ioctl interface

src/btrfs2s3/_internal/btrfsioctl.py, tests/resolver/keep_backup_of_snapshot_test.py, tests/resolver/keep_most_recent_snapshot_test.py, tests/resolver/keep_send_ancestors_of_backups_test.py, tests/resolver/keep_snapshot_and_backup_for_time_span_test.py, tests/resolver/marker_test.py, tests/resolver/resolve_test.py
this just improves conciseness, I should have done this in the previous change
=> test(resolver): give SubvolInfo default values

tests/resolver/index_test.py, tests/resolver/keep_backup_of_snapshot_test.py, tests/resolver/keep_most_recent_snapshot_test.py, tests/resolver/keep_send_ancestors_of_backups_test.py, tests/resolver/keep_snapshot_and_backup_for_time_span_test.py, tests/resolver/resolve_test.py, tests/s3/iter_backups_test.py
this is more concise and readable than uuid4().bytes everywhere
=> test: use _u() random uuid idiom

.pre-commit-config.yaml, src/btrfs2s3/_internal/planner.py, src/btrfs2s3/_internal/s3.py, src/btrfs2s3/_internal/stream_uploader.py, tests/commands/update2/invocation_test.py, tests/commands/update2/print_plan_test.py, tests/conftest.py, tests/planner/actions_test.py, tests/planner/assess_test.py, tests/planner/assess_with_actions_integration_test.py, tests/planner/remote_test.py, tests/s3/iter_backups_test.py, tests/stream_uploader/upload_non_seekable_stream_via_tempfile_test.py
ref: https://github.com/youtype/boto3-stubs/blob/ae0afbba8752069802fda9c69472c86c50b7475b/README.md#boto3-stubs
=> refactor(types): migrate boto3-stubs -> types-boto3

pyproject.toml
=> build(deps): bump setuptools

.pre-commit-config.yaml, pyproject.toml, test-requirements.txt
I synthesized this from https://github.com/executablebooks/mdformat-plugin/tree/38530fd7fa9eeac302cb89314ab043147db7e51a/
=> build(test): move test-requirements.txt to extras

src/btrfs2s3/_internal/commands/printing.py, src/btrfs2s3/_internal/commands/update2.py, tests/commands/update2/print_plan_test.py
to facilitate addition of other commands
=> refactor(update2.py): refactor out printing functionality
